name       : kpackage
version    : 5.77.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kpackage-5.77.0.tar.xz : e91f8dd81f4d2f5730ec444eb8acbe7e1891fa31df2fe01886ae0012d9ec2bd3
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
optimize   : lto
summary    : Installation and loading of additional content as packages
description: |
    Installation and loading of additional content (scripts, images...) as packages.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
