name       : kpackage
version    : 5.94.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/kpackage-5.94.0.tar.xz : 4d4c9c2920c9b10f6879f2d8a29426615e9e6b13d78c0b751ea4a656b4baf414
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Installation and loading of additional content as packages
description: |
    Installation and loading of additional content (scripts, images...) as packages.
optimize   : lto
builddeps  :
    - karchive-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
