name       : kpackage
version    : 5.53.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kpackage-5.53.0.tar.xz : 2a272077b595639d4880fcbcab4b7102aa08db1a5083bb219f746be24f5c94be
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Installation and loading of additional content as packages
description: |
    Installation and loading of additional content (scripts, images...) as packages.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
