name       : kpackage
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/kpackage-5.25.0.tar.xz : 47c641dc173d5b597937b00fe2e01a0058916273278a7d44f4c3ae932b753013
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Installation and loading of additional content as packages
description: |
    Installation and loading of additional content (scripts, images...) as packages.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
rundeps    :
    - devel:
        - kcoreaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
