name       : kpackage
version    : 5.52.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kpackage-5.52.0.tar.xz : 3997add0d4b4fc7a6f9fa86a2dbec2e4f419c8b2e1e2c02fce6d2f6839466814
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Installation and loading of additional content as packages
description: |
    Installation and loading of additional content (scripts, images...) as packages.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
