name       : kpackage
version    : 5.83.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kpackage-5.83.0.tar.xz : ac950083ba66429e5e7c0898dd911210a22b12a9421ddc05c28d74dcbdb7801e
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Installation and loading of additional content as packages
description: |
    Installation and loading of additional content (scripts, images...) as packages.
optimize   : lto
builddeps  :
    - karchive-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
