name       : kpackage
version    : 5.38.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.38/kpackage-5.38.0.tar.xz : b6eb027aa8fbb0a45d87b026ae7117f14c08385628b5da5ba55994f7f01c926c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Installation and loading of additional content as packages
description: |
    Installation and loading of additional content (scripts, images...) as packages.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
