name       : kpackage
version    : 5.67.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kpackage-5.67.0.tar.xz : 55ab8e9e2546a65aff1ed7203d203f3a4ec1d17adfc77abaee74ff73823da6e3
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Installation and loading of additional content as packages
description: |
    Installation and loading of additional content (scripts, images...) as packages.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
