name       : kpackage
version    : 5.66.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kpackage-5.66.0.tar.xz : ae848a72e789a80d4a9d0346e90cb1038ebc784da6e7ff645411edd878554ab5
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Installation and loading of additional content as packages
description: |
    Installation and loading of additional content (scripts, images...) as packages.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
